### PR TITLE
[add] ynh.fr

### PR DESCRIPTION
**Pull request by frju365**

### CODE REVIEW

**Comment by frju365** [comment]
Perhaps, we could have this merged and configured when YNH Stretch will be released ?

**Comment by frju365** [comment]
@zamentur do you know how to integrate that on the server ? Because I know a bit Bind setting but I'm not sure if I will not break everything.

**Comment by zamentur** [comment]
Yep I think I could succeed in added that on our infra. We should be careful...

**Comment by frju365** [comment]
ok. I know. It's the reason I prefer not to do this modification.
It would be nice to have it when the stretch version will be officially release. :-)

**Pull request merged**
